### PR TITLE
Add separate header option

### PR DESCRIPTION
**Pull request by rovo89**
For most generated/dynamic data there's a fixed header. It's easier to use and more intuitive to use for me to specify this header via a separate option rather than prepending it to `rows` and setting `header_row` to true.

Again, I didn't add documentation and tests yet, I can add it based on the interest in this PR.

### CODE REVIEW

**Comment by neilb** [comment]
I like this option. I think it can be done with a change to the code in one place. Right after `my @rows = @$rows;`, we can add:

    if (exists $param{header}) {
        unshift(@rows, $param{header});
        $param{header_row} = 1;
    }

If you want to do this, and add a new test file, and documentation, that'd be great.

If you don't have time in the next day or so, let me know, and I'll just do it :-)

**Comment by neilb** [comment]
Just had a thought: should also add a check for both `header` and `header_row` being set in the input – that should croak.

**Comment by neilb** [comment]
I've added a "header" option, prompted by this PR. Thanks!

**Comment by rovo89** [comment]
Thanks for adding the option! And sorry for the late response, was off for a few days.

**Pull request closed without merging**
